all: ch2_exercise_2_16 ch2_exercise_2_17 ch2_exercise_2_18 ch2_exercise_2_19

ch2_exercise_2_16: ch2_exercise_2_16.o
	g++ -o ch2_exercise_2_16 ch2_exercise_2_16.o

ch2_exercise_2_16.o: ch2_exercise_2_16.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_16.cpp

ch2_exercise_2_17: ch2_exercise_2_17.o
	g++ -o ch2_exercise_2_17 ch2_exercise_2_17.o

ch2_exercise_2_17.o: ch2_exercise_2_17.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_17.cpp

ch2_exercise_2_18: ch2_exercise_2_18.o
	g++ -o ch2_exercise_2_18 ch2_exercise_2_18.o

ch2_exercise_2_18.o: ch2_exercise_2_18.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_18.cpp

ch2_exercise_2_19: ch2_exercise_2_19.o
	g++ -o ch2_exercise_2_19 ch2_exercise_2_19.o

ch2_exercise_2_19.o: ch2_exercise_2_19.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_19.cpp

clean:
	rm -f ch2_exercise_2_16
	rm -f ch2_exercise_2_16.o
	rm -f ch2_exercise_2_17
	rm -f ch2_exercise_2_17.o
	rm -f ch2_exercise_2_18
	rm -f ch2_exercise_2_18.o
	rm -f ch2_exercise_2_19
	rm -f ch2_exercise_2_19.o
