all: ch2_exercise_2_16 ch2_exercise_2_17 ch2_exercise_2_18 ch2_exercise_2_19 ch2_exercise_2_20 ch2_exercise_2_21 ch2_exercise_2_23 ch2_exercise_2_24 ch2_exercise_2_25 ch2_exercise_2_26 ch2_exercise_2_27 ch2_exercise_2_28 ch2_exercise_2_29 ch2_exercise_2_30 ch2_exercise_2_31

ch2_exercise_2_16: ch2_exercise_2_16.o
	g++ -o ch2_exercise_2_16 ch2_exercise_2_16.o

ch2_exercise_2_16.o: ch2_exercise_2_16.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_16.cpp

ch2_exercise_2_17: ch2_exercise_2_17.o
	g++ -o ch2_exercise_2_17 ch2_exercise_2_17.o

ch2_exercise_2_17.o: ch2_exercise_2_17.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_17.cpp

ch2_exercise_2_18: ch2_exercise_2_18.o
	g++ -o ch2_exercise_2_18 ch2_exercise_2_18.o

ch2_exercise_2_18.o: ch2_exercise_2_18.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_18.cpp

ch2_exercise_2_19: ch2_exercise_2_19.o
	g++ -o ch2_exercise_2_19 ch2_exercise_2_19.o

ch2_exercise_2_19.o: ch2_exercise_2_19.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_19.cpp

ch2_exercise_2_20: ch2_exercise_2_20.o
	g++ -o ch2_exercise_2_20 ch2_exercise_2_20.o

ch2_exercise_2_20.o: ch2_exercise_2_20.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_20.cpp

ch2_exercise_2_21: ch2_exercise_2_21.o
	g++ -o ch2_exercise_2_21 ch2_exercise_2_21.o

ch2_exercise_2_21.o: ch2_exercise_2_21.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_21.cpp

ch2_exercise_2_23: ch2_exercise_2_23.o
	g++ -o ch2_exercise_2_23 ch2_exercise_2_23.o

ch2_exercise_2_23.o: ch2_exercise_2_23.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_23.cpp

ch2_exercise_2_24: ch2_exercise_2_24.o
	g++ -o ch2_exercise_2_24 ch2_exercise_2_24.o

ch2_exercise_2_24.o: ch2_exercise_2_24.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_24.cpp

ch2_exercise_2_25: ch2_exercise_2_25.o
	g++ -o ch2_exercise_2_25 ch2_exercise_2_25.o

ch2_exercise_2_25.o: ch2_exercise_2_25.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_25.cpp

ch2_exercise_2_26: ch2_exercise_2_26.o
	g++ -o ch2_exercise_2_26 ch2_exercise_2_26.o

ch2_exercise_2_26.o: ch2_exercise_2_26.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_26.cpp

ch2_exercise_2_27: ch2_exercise_2_27.o
	g++ -o ch2_exercise_2_27 ch2_exercise_2_27.o

ch2_exercise_2_27.o: ch2_exercise_2_27.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_27.cpp

ch2_exercise_2_28: ch2_exercise_2_28.o
	g++ -o ch2_exercise_2_28 ch2_exercise_2_28.o

ch2_exercise_2_28.o: ch2_exercise_2_28.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_28.cpp

ch2_exercise_2_29: ch2_exercise_2_29.o
	g++ -o ch2_exercise_2_29 ch2_exercise_2_29.o

ch2_exercise_2_29.o: ch2_exercise_2_29.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_29.cpp

ch2_exercise_2_30: ch2_exercise_2_30.o
	g++ -o ch2_exercise_2_30 ch2_exercise_2_30.o

ch2_exercise_2_30.o: ch2_exercise_2_30.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_30.cpp

ch2_exercise_2_31: ch2_exercise_2_31.o
	g++ -o ch2_exercise_2_31 ch2_exercise_2_31.o

ch2_exercise_2_31.o: ch2_exercise_2_31.cpp
	g++ -Wall -std=c++14 -g -O0 -pedantic-errors -c ch2_exercise_2_31.cpp

clean:
	rm -f ch2_exercise_2_16
	rm -f ch2_exercise_2_16.o
	rm -f ch2_exercise_2_17
	rm -f ch2_exercise_2_17.o
	rm -f ch2_exercise_2_18
	rm -f ch2_exercise_2_18.o
	rm -f ch2_exercise_2_19
	rm -f ch2_exercise_2_19.o
	rm -f ch2_exercise_2_20
	rm -f ch2_exercise_2_20.o
	rm -f ch2_exercise_2_21
	rm -f ch2_exercise_2_21.o
	rm -f ch2_exercise_2_23
	rm -f ch2_exercise_2_23.o
	rm -f ch2_exercise_2_24
	rm -f ch2_exercise_2_24.o
	rm -f ch2_exercise_2_25
	rm -f ch2_exercise_2_25.o
	rm -f ch2_exercise_2_26
	rm -f ch2_exercise_2_26.o
	rm -f ch2_exercise_2_27
	rm -f ch2_exercise_2_27.o
	rm -f ch2_exercise_2_28
	rm -f ch2_exercise_2_28.o
	rm -f ch2_exercise_2_29
	rm -f ch2_exercise_2_29.o
	rm -f ch2_exercise_2_30
	rm -f ch2_exercise_2_30.o
	rm -f ch2_exercise_2_31
	rm -f ch2_exercise_2_31.o